// snippets/react/form-login.jsx
// snippet: form-login
// category: forms
// rationale: components/forms.md
// requires: tailwindcss

import { useState } from 'react';

export function LoginForm({ onSubmit }) {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [remember, setRemember] = useState(false);
  const [errors, setErrors] = useState({});
  const [loading, setLoading] = useState(false);

  const validate = () => {
    const errs = {};
    if (!email) errs.email = 'Email is required';
    else if (!/\S+@\S+\.\S+/.test(email)) errs.email = 'Enter a valid email';
    if (!password) errs.password = 'Password is required';
    else if (password.length < 8) errs.password = 'Password must be at least 8 characters';
    return errs;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    const errs = validate();
    setErrors(errs);
    if (Object.keys(errs).length > 0) return;

    setLoading(true);
    try {
      await onSubmit?.({ email, password, remember });
    } finally {
      setLoading(false);
    }
  };

  const inputClass = (field) =>
    `w-full border rounded-lg px-3 py-2.5 text-base bg-white dark:bg-slate-700 text-slate-900 dark:text-white placeholder-slate-400 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none min-h-11 ${
      errors[field] ? 'border-red-500 dark:border-red-400' : 'border-slate-300 dark:border-slate-600'
    }`;

  return (
    <form onSubmit={handleSubmit} className="space-y-4" noValidate>
      <div>
        <label htmlFor="login-email" className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1.5">
          Email
        </label>
        <input
          id="login-email"
          type="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          placeholder="you@example.com"
          className={inputClass('email')}
          autoComplete="email"
        />
        {errors.email && <p className="mt-1.5 text-sm text-red-600 dark:text-red-400">{errors.email}</p>}
      </div>

      <div>
        <div className="flex items-center justify-between mb-1.5">
          <label htmlFor="login-password" className="block text-sm font-medium text-slate-700 dark:text-slate-300">
            Password
          </label>
          <a href="#" className="text-sm text-blue-600 dark:text-blue-400 hover:underline">Forgot password?</a>
        </div>
        <input
          id="login-password"
          type="password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          placeholder="Enter your password"
          className={inputClass('password')}
          autoComplete="current-password"
        />
        {errors.password && <p className="mt-1.5 text-sm text-red-600 dark:text-red-400">{errors.password}</p>}
      </div>

      <div className="flex items-center gap-2">
        <input
          id="login-remember"
          type="checkbox"
          checked={remember}
          onChange={(e) => setRemember(e.target.checked)}
          className="w-4 h-4 rounded border-slate-300 dark:border-slate-600 text-blue-600 focus:ring-2 focus:ring-blue-500"
        />
        <label htmlFor="login-remember" className="text-sm text-slate-600 dark:text-slate-400">
          Remember me
        </label>
      </div>

      <button
        type="submit"
        disabled={loading}
        className="w-full bg-blue-600 hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed text-white font-medium py-2.5 rounded-lg text-base transition-colors min-h-11 flex items-center justify-center gap-2"
      >
        {loading && (
          <svg className="animate-spin w-4 h-4" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
          </svg>
        )}
        {loading ? 'Signing in...' : 'Sign In'}
      </button>

      <p className="text-center text-sm text-slate-600 dark:text-slate-400">
        Don't have an account?{' '}
        <a href="#" className="text-blue-600 dark:text-blue-400 hover:underline font-medium">Sign up</a>
      </p>
    </form>
  );
}

// snippets/svelte/form-login.svelte
<!-- snippet: form-login
     category: forms
     rationale: components/forms.md
     requires: tailwindcss
-->

<script>
  let { onSubmit } = $props();

  let email = $state('');
  let password = $state('');
  let remember = $state(false);
  let errors = $state({});
  let loading = $state(false);

  function validate() {
    const errs = {};
    if (!email) errs.email = 'Email is required';
    else if (!/\S+@\S+\.\S+/.test(email)) errs.email = 'Enter a valid email';
    if (!password) errs.password = 'Password is required';
    else if (password.length < 8) errs.password = 'Password must be at least 8 characters';
    return errs;
  }

  async function handleSubmit(e) {
    e.preventDefault();
    const errs = validate();
    errors = errs;
    if (Object.keys(errs).length > 0) return;

    loading = true;
    try {
      await onSubmit?.({ email, password, remember });
    } finally {
      loading = false;
    }
  }

  function inputClass(field) {
    return `w-full border rounded-lg px-3 py-2.5 text-base bg-white dark:bg-slate-700 text-slate-900 dark:text-white placeholder-slate-400 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none min-h-11 ${
      errors[field] ? 'border-red-500 dark:border-red-400' : 'border-slate-300 dark:border-slate-600'
    }`;
  }
</script>

<form onsubmit={handleSubmit} class="space-y-4" novalidate>
  <div>
    <label for="login-email" class="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1.5">
      Email
    </label>
    <input
      id="login-email"
      type="email"
      bind:value={email}
      placeholder="you@example.com"
      class={inputClass('email')}
      autocomplete="email"
    />
    {#if errors.email}
      <p class="mt-1.5 text-sm text-red-600 dark:text-red-400">{errors.email}</p>
    {/if}
  </div>

  <div>
    <div class="flex items-center justify-between mb-1.5">
      <label for="login-password" class="block text-sm font-medium text-slate-700 dark:text-slate-300">
        Password
      </label>
      <a href="#" class="text-sm text-blue-600 dark:text-blue-400 hover:underline">Forgot password?</a>
    </div>
    <input
      id="login-password"
      type="password"
      bind:value={password}
      placeholder="Enter your password"
      class={inputClass('password')}
      autocomplete="current-password"
    />
    {#if errors.password}
      <p class="mt-1.5 text-sm text-red-600 dark:text-red-400">{errors.password}</p>
    {/if}
  </div>

  <div class="flex items-center gap-2">
    <input
      id="login-remember"
      type="checkbox"
      bind:checked={remember}
      class="w-4 h-4 rounded border-slate-300 dark:border-slate-600 text-blue-600 focus:ring-2 focus:ring-blue-500"
    />
    <label for="login-remember" class="text-sm text-slate-600 dark:text-slate-400">
      Remember me
    </label>
  </div>

  <button
    type="submit"
    disabled={loading}
    class="w-full bg-blue-600 hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed text-white font-medium py-2.5 rounded-lg text-base transition-colors min-h-11 flex items-center justify-center gap-2"
  >
    {#if loading}
      <svg class="animate-spin w-4 h-4" fill="none" viewBox="0 0 24 24">
        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"></path>
      </svg>
    {/if}
    {loading ? 'Signing in...' : 'Sign In'}
  </button>

  <p class="text-center text-sm text-slate-600 dark:text-slate-400">
    Don't have an account?
    <a href="#" class="text-blue-600 dark:text-blue-400 hover:underline font-medium">Sign up</a>
  </p>
</form>
